### PR TITLE
#169571349 Get all diary entries

### PR DESCRIPTION
**Pull request by Muhire-Josue**
ss1#### What does this PR do?

- It displays all diary entries of a user

#### Description of Task to be completed?

- add the database to all entries endpoint

- Test for this endpoint

#### How should this be manually tested?

- Use this link in postman: https://mydiary-api-host.herokuapp.com/api/v1/entries

#### Any background context you want to provide?

- N/A

#### What are the relevant pivotal tracker stories?

- [169571349](https://www.pivotaltracker.com/story/show/169571349)

#### Screenshots (if appropriate)
all-diaries

### CODE REVIEW

**Review by ekumamait — COMMENTED** [review]
Correct the PR title

**Comment by Muhire-Josue** [comment]
> Correct the PR title

Done.

**Comment by ekumamait** [comment]
The PR title is misleading, is this PR for `getting all entries` or `deleting an entry`?

**Comment by Muhire-Josue** [comment]
> The PR title is misleading, is this PR for `getting all entries` or `deleting an entry`?

It's getting all entries, I see why you are confused, the tittle was deleting but the PR is getting all entries. I have changed it now.

**Comment by ekumamait** [comment]
> > The PR title is misleading, is this PR for `getting all entries` or `deleting an entry`?
> 
> It's getting all entries, I see why you are confused, the title was deleting but the PR is getting all entries. I have changed it now.

The Story ID in the PR title comes before the description `#169571349 Get all diary entries`

**Comment by Muhire-Josue** [comment]
> > > The PR title is misleading, is this PR for `getting all entries` or `deleting an entry`?
> > 
> > 
> > It's getting all entries, I see why you are confused, the title was deleting but the PR is getting all entries. I have changed it now.
> 
> The Story ID in the PR title comes before the description `#169571349 Get all diary entries``

I have changed the title.

**Comment by ekumamait** [comment]
LGTM

**Pull request merged**
